### PR TITLE
Fix/demo bugs

### LINKED ISSUE #170: Bug Fixes
- [x] Vendor companies are shown in add user
- [x] Company balance not visible on users list
- [x] Payment type of zero orders changed to cash
- [x] Order details print issue

### PR DESCRIPTION
**Pull request by OmerAli277**
closes #170

### CODE REVIEW

File: src/components/sales/AddEditProduct.vue [hunk 1]
```diff
@@ -331,9 +331,13 @@ export default defineComponent({
         if (this.product.productVariants.length > 1) {
           const deleteProductVariantID = this.product.productVariants[index].id;
           // Delete Variant
-          this.deleteProductVariant(deleteProductVariantID);
-          this.updateDeleteLastVarient = '';
-          this.product.productVariants.splice(index, 1);
+          if (deleteProductVariantID) {
+            this.deleteProductVariant(deleteProductVariantID);
+            this.updateDeleteLastVarient = '';
+            this.product.productVariants.splice(index, 1);
```
Comment (ammarhaiderak) [inline src/components/sales/AddEditProduct.vue:337]: why do we have to manually update the list. Should be updated automatically as the state changes after delete and getter should have updated list.

Comment (OmerAli277) [reply src/components/sales/AddEditProduct.vue:337]: @ammarhaiderak Then, we have manually fetch the product after each insertion and deletion, that's why.

**Review by ammarhaiderak — APPROVED** [review]
